# fly.toml app configuration file
app = "redflag"
primary_region = "ewr"
console_command = "/rails/bin/rails console"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
  
  [[http_service.domains]]
    name = "redflag.procurementexpress.com"
    zone = "procurementexpress.com"

[checks]
  [checks.status]
    port = 3000
    type = "http"
    interval = "10s"
    timeout = "2s"
    grace_period = "5s"
    method = "GET"
    path = "/up"
    protocol = "http"
    tls_skip_verify = false

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024

[mounts]
  source = "storage"
  destination = "/rails/storage"

[[statics]]
  guest_path = "/rails/public"
  url_prefix = "/"

[env]
  PORT = "3000"
  DATABASE_URL = "sqlite3:///rails/storage/production.sqlite3"
  SOLID_QUEUE_IN_PUMA = "true"
  JOB_CONCURRENCY = "2"
  # Admin credentials for basic auth (real credentials should be set as secrets)
  ADMIN_USERNAME = "admin"
  # Email configuration
  ADMIN_EMAIL = "leads@redflagapp.com"
  # For security, don't set the real password here - use secrets

# Using SolidQueue for background jobs (no Redis needed)
# Sensitive configuration is stored as secrets (POSTMARK_API_TOKEN, ADMIN_PASSWORD)
