# fly.toml app configuration file
app = "redflag"
primary_region = "ewr"
console_command = "/rails/bin/rails console"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[checks]
  [checks.status]
    port = 3000
    type = "http"
    interval = "10s"
    timeout = "2s"
    grace_period = "5s"
    method = "GET"
    path = "/up"
    protocol = "http"
    tls_skip_verify = false

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024

[mounts]
  source = "storage"
  destination = "/rails/storage"

[[statics]]
  guest_path = "/rails/public"
  url_prefix = "/"

[env]
  PORT = "3000"
  DATABASE_URL = "sqlite3:///rails/storage/production.sqlite3"
  SOLID_QUEUE_IN_PUMA = "true"
  # Redis URL will be set via secrets with: flyctl secrets set REDIS_URL=redis://redflag-redis.internal:6379

# Redis is deployed separately as redflag-redis app
# No need to define Redis service here as it's handled by redis-fly.toml
